import type {
  ElementKey, SiteConfig, ThemeCustom, ThemeName, ThemeOverrides, TokenKey,
} from "@/sections/types";

export type { ElementKey, ThemeCustom, ThemeOverrides, TokenKey };

/* ------------------------------------------------------------------ tokens */

export const TOKEN_KEYS = ["bg", "surf", "ink", "mut", "acc", "accInk", "line", "soft"] as const satisfies readonly TokenKey[];

/** CSS custom property each token writes to. Consumed by `@theme inline` in globals.css. */
const TOKEN_VAR: Record<TokenKey, string> = {
  bg: "--p-bg", surf: "--p-surf", ink: "--p-ink", mut: "--p-mut",
  acc: "--p-acc", accInk: "--p-acc-ink", line: "--p-line", soft: "--p-soft",
};

export const TOKEN_LABEL: Record<TokenKey, string> = {
  bg: "Page background",
  surf: "Card surface",
  ink: "Body text",
  mut: "Muted text",
  acc: "Accent",
  accInk: "Text on accent",
  line: "Borders",
  soft: "Soft fill",
};

export type Tokens = Record<TokenKey, string>;

/**
 * The three presets. This file is the single source of truth — the CSS for them
 * is generated by `themeCss()` below rather than duplicated in globals.css, so a
 * preset can never drift between the stylesheet and the editor's swatches.
 */
export const PRESETS: Record<ThemeName, { label: string; tokens: Tokens }> = {
  paper: {
    label: "Paper",
    tokens: {
      bg: "#FAFAF7", surf: "#FFFFFF", ink: "#14171C", mut: "#5C6573",
      acc: "#1B4D3E", accInk: "#FFFFFF", line: "#E5E3DC", soft: "#EEF1EE",
    },
  },
  graphite: {
    label: "Graphite",
    tokens: {
      bg: "#0F1114", surf: "#171A20", ink: "#EDEFF3", mut: "#99A2AF",
      acc: "#F5A54A", accInk: "#1A1206", line: "#242932", soft: "#1C2028",
    },
  },
  signal: {
    label: "Signal",
    tokens: {
      bg: "#F2F4F7", surf: "#FFFFFF", ink: "#0E1A2B", mut: "#54637A",
      acc: "#E8552D", accInk: "#FFFFFF", line: "#DDE3EB", soft: "#E8EDF4",
    },
  },
};

export const THEMES = (Object.keys(PRESETS) as ThemeName[]).map((id) => ({
  id, label: PRESETS[id].label, swatch: PRESETS[id].tokens.acc,
}));

export const isTheme = (v: unknown): v is ThemeName =>
  typeof v === "string" && v in PRESETS;

/* ---------------------------------------------------------------- elements */

export const ELEMENT_KEYS = ["h1", "h2", "h3", "p", "a", "eyebrow"] as const satisfies readonly ElementKey[];

/**
 * Selector each element override writes to, relative to the themed root.
 * Rules are emitted UNLAYERED so they beat Tailwind's utilities layer —
 * otherwise `text-mut` on a paragraph would silently win over your override.
 * They are only emitted when you actually set a colour.
 */
const ELEMENT_SELECTOR: Record<ElementKey, string> = {
  h1: "h1",
  h2: "h2",
  h3: "h3",
  p: "p",
  a: "a:not(.pill):not(.pill-ghost)",
  eyebrow: ".eyebrow",
};

export const ELEMENT_LABEL: Record<ElementKey, string> = {
  h1: "Page title (h1)",
  h2: "Section headings (h2)",
  h3: "Card headings (h3)",
  p: "Paragraphs (p)",
  a: "Links (a)",
  eyebrow: "Eyebrow labels",
};

/* ------------------------------------------------------------ customisation */

/* ------------------------------------------------------------- sanitisation */

/**
 * Custom CSS is authored by the signed-in owner, but it is still injected into a
 * <style> tag, so strip the one character that could close the tag early, plus
 * @import (fetches a third-party stylesheet at render time) and two legacy
 * script vectors. `>` is deliberately kept — child combinators are legitimate.
 */
export function sanitizeCss(input: unknown, max = 20_000): string {
  return String(input ?? "")
    .slice(0, max)
    .replace(/</g, "")
    .replace(/@import[^;]*;?/gi, "")
    .replace(/expression\s*\(/gi, "(")
    .replace(/javascript\s*:/gi, "")
    .trim();
}

const COLOR_RE =
  /^(#[0-9a-f]{3,8}|(?:rgb|rgba|hsl|hsla|oklch|lab|color-mix)\([^;{}<>]*\)|[a-z-]{3,24})$/i;

/** Accepts a hex, a colour function, or a CSS colour keyword. Rejects anything else. */
export function isColor(v: unknown): v is string {
  return typeof v === "string" && v.length <= 120 && COLOR_RE.test(v.trim());
}

/* ----------------------------------------------------------------- resolver */

export function resolveTokens(theme: ThemeName, overrides?: ThemeOverrides): Tokens {
  const custom = overrides?.[theme]?.tokens ?? {};
  const out = { ...PRESETS[theme].tokens };
  for (const k of TOKEN_KEYS) {
    const v = custom[k];
    if (isColor(v)) out[k] = v.trim();
  }
  return out;
}

const escapeAttr = (v: string) => v.replace(/["\\]/g, "");

/**
 * The complete stylesheet for a config: preset tokens (with overrides applied),
 * any element colour rules, and the global custom CSS. Rendered into a <style>
 * by <ThemeStyle>, which both the public site and the editor preview use, so
 * what you see in the editor is byte-for-byte what ships.
 */
export function themeCss(config: SiteConfig): string {
  const theme = isTheme(config.theme) ? config.theme : "paper";
  const scope = `[data-theme="${escapeAttr(theme)}"]`;
  const tokens = resolveTokens(theme, config.themeOverrides);

  const vars = TOKEN_KEYS.map((k) => `${TOKEN_VAR[k]}:${tokens[k]}`).join(";");
  const out: string[] = [`${scope}{${vars}}`];

  const elements = config.themeOverrides?.[theme]?.elements ?? {};
  for (const key of ELEMENT_KEYS) {
    const v = elements[key];
    if (!isColor(v)) continue;
    // Inverted surfaces (the contact band) opt out so an h2 override cannot
    // make their heading unreadable against the accent background.
    out.push(`${scope} ${ELEMENT_SELECTOR[key]}:not([data-invert] *){color:${v.trim()}}`);
  }

  const custom = sanitizeCss(config.customCss);
  if (custom) out.push(`${scope}{${custom}}`);

  return out.join("\n");
}

/** Per-section CSS, scoped to that section's wrapper via native CSS nesting. */
export function sectionCss(id: string, css: unknown): string {
  const body = sanitizeCss(css, 8_000);
  if (!body) return "";
  return `[data-sid="${escapeAttr(id)}"]{${body}}`;
}

export function allSectionCss(config: SiteConfig): string {
  return config.sections
    .map((s) => sectionCss(s.id, s.css))
    .filter(Boolean)
    .join("\n");
}
